views:
  - id: 'c4c9d4dc-04ce-428d-bfdb-0445e8bdd9f7'
    name: 'Datapipe View 1'
    type: 'data-pipe'
    default: true
    description: 'Default view for data pipe.'
    modelObjects:
      - id: '6a5a58e7-60b3-47b8-a4db-22e618250c53'
  - id: '080257fb-bbdb-4394-bdd8-0d12c03f7db5'
    name: 'Datamodel View 1'
    type: 'data-model'
    default: true
    description: 'Default view for data model.'
    modelObjects: []
